name: urlshortener
version: 0.1.0.0
github: "githubuser/urlshortener"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/urlshortener#readme>

dependencies:
  - aeson == 1.5.6.0
  - base >= 4.7 && < 5
  - directory == 1.3.6.0
  - http-client == 0.6.4.1
  - http-types == 0.12.3
  - hspec == 2.7.10
  - monad-logger == 0.3.36
  - mtl == 2.2.2
  - persistent == 2.13.1.2
  - persistent-template == 2.12.0.0
  - persistent-sqlite == 2.13.0.3
  - port-utils == 0.2.1.0
  - QuickCheck == 2.14.2
  - quickcheck-instances == 0.3.25.2
  - servant == 0.18.3
  - servant-server == 0.18.3
  - servant-client == 0.18.3
  - servant-client-core == 0.18.3
  - stm == 2.5.0.1
  - text == 1.2.4.1
  - wai == 3.2.3
  - warp == 3.3.17


library:
  source-dirs: src

executables:
  urlshortener-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - urlshortener

tests:
  urlshortener-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - urlshortener
